apiVersion: v1
kind: Service
metadata:
  name: swish-python3
  namespace: swish
spec:
  type: NodePort
  selector:
    app: swish-python3
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
